### ISSUE TITLE
tutorial

### ISSUE THREAD

**Issue by MyNewBie** [taktoa/pianoman#2]
any tutorial ? youtube video or description how to setup and install requirements ?

**Comment by taktoa** [comment]
Unfortunately this project is not really ready for end-user use. If you do want to install it, you'll at least have to learn how to use [Nix](https://nixos.org/nix/manual) as a basic prerequisite.

**Comment by MyNewBie** [comment]
ok , thanks for answer . I have an personal question , is there any other music bot for Linux ?
caz I really don't want use sinusbot and ts3musicbot.net .

**Comment by taktoa** [comment]
On Linux you can run a TeamSpeak 3 client and then set the record device to be the output of another program in PulseAudio (e.g.: with `pavucontrol`). That is actually the basis for how `pianoman` is designed, except we (me and @cleverca22) wanted the TS client to be headless (no GUI), so we wrote a plugin that exposes the entire TS3 plugin API over a ZeroMQ socket and replaced the Qt that it uses with one that can use the `offscreen` Qt Platform Abstraction (QPA). We also launch a separate PulseAudio server so it doesn't interfere with other programs on the same computer, though we currently have issues with launching that PulseAudio server without an ambient DBus server running (so it's not quite headless yet).

**Comment by MyNewBie** [comment]
hmm I was looking for somthinge have webinterface , ok thanks anyway .
